[tasks.generate-schemas]
script_runner = "@rust"
script = '''
use std::fs;
use std::process::Command;

fn main() -> std::io::Result<()> {
    let _ = fs::remove_dir_all("schema");
    let _ = fs::remove_dir_all("schemas");
    fs::create_dir("schemas")?;
    println!("Done");

    let contracts = vec![
        "fixed-odds-market",
        "parimutuel-market",
    ];

    for contract in contracts {
        println!("{}", contract);

        let output = Command::new("cargo")
            .arg("run")
            .arg("--package")
            .arg(contract)
            .arg("--bin")
            .arg("schema")
            .output()
            .expect("failed to execute process");

        println!("status: {}", output.status);
        println!("stdout: {}", String::from_utf8_lossy(&output.stdout));
        println!("stderr: {}", String::from_utf8_lossy(&output.stderr));

        fs::create_dir(format!("schemas/{}", contract))?;

        fs::rename(
            format!("schema/{}.json", contract),
            format!("schemas/{}/{}.json", contract, contract),
        )?;
    }

    let _ = fs::remove_dir_all("schema");

    Ok(())
}
'''
